# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US

reviews:
  auto_review:
    enabled: true
    drafts: false
  request_changes_workflow: true
  review_progress: true
  fail_commit_status: true
  high_level_summary: true
  poem: false

chat:
  auto_reply: true
